version: '3'
services:
  myapp:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=laravel
      - DB_DATABASE=laravel
      - DB_PASSWORD=laravel
    volumes:
      - './my-project:/app'
    depends_on:
      - db
  db:
    image: 'mysql:5.7'
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - MYSQL_ROOT_PASSWORD=laravel
    ports:
      - '3306:3306'
    volumes:
      - 'db_data:/var/lib/mysql'
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    environment:
      - PMA_HOST=db
    ports:
      - '8080:80'
volumes:
  db_data: